### ISSUE TITLE
Invisible Grass

### ISSUE THREAD

**Issue by MCAlagaesia** [MCAlagaesiaNetwork/Fairth#100]
One of the grass textures is invisible. It should be removed or replaced with an alternate texture.

![2021-11-07_17 17 53](https://user-images.githubusercontent.com/10643460/140634659-763580a9-554f-4572-a90f-0b60b40e8ab6.png)

**Comment by Sjmarf** [comment]
Fixed :)

The issue was not that the texture was invisible, it was that the grass pictured was too short. Minecraft renders Grass a couple of pixels into the ground, and the texture was only a couple of pixels tall. The texture has now been removed.

https://github.com/MCAlagaesiaNetwork/Fairth/pull/112
