### ISSUE TITLE
Logs to 32x

### ISSUE THREAD

**Issue by VoidShadow204** [MCAlagaesiaNetwork/Fairth#39]
There are already leaves on 32x with a few extras in the 3D model. But for great trees we also need a new Log texture. 
There could be diffrent textures, but they have to match on the boarders. 

- [ ] Oak
- [ ] Spruce
- [ ] Birch
- [ ] Jungle
- [ ] Dark Oak
- [ ] Acacia

**Comment by MCAlagaesia** [comment]
To comment on your note about different textures, perhaps one easy variation would be to add knots. The borders can match up perfectly since the knot doesn't need to take up a whole 32x32 pixels.

![image](https://user-images.githubusercontent.com/10643460/67263371-ab51b600-f4f3-11e9-9f00-5e03023798bf.png)
Photo by A Bremner

**Comment by VoidShadow204** [comment]
I also was thinking about sth. like this, I was also thinking about little boughs, but it would be also visible on houses and every other structure, aside from trees...
![log](https://user-images.githubusercontent.com/47636390/67364725-6a4bb700-f570-11e9-8173-c3a202961ce0.png)

**Comment by MCAlagaesia** [comment]
Yeah, any changes to the model might suit trees, but wouldn't be good for building. I think we need to limit ourselves to texture variations.

**Comment by VoidShadow204** [comment]
Closed in order to transform this Recourcepack to an Faithful32x Addon
